repos:
- repo: https://github.com/psf/black
  rev: 25.9.0
  hooks:
  - id: black      # Run Black - the uncompromising Python code formatter
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: end-of-file-fixer      # Ensure existence of newline characters at file ends
  - id: check-yaml      # Make sure that contained YAML files are well-formed
  - id: trailing-whitespace      # Trim trailing whitespace of all sorts
  - id: check-added-large-files      # Apply a file size limit of 500kB
    args:
      - --maxkb=2048
  - id: check-toml      # Simple parser validation of e.g. pyproject.toml
  - id: check-json      # Check validity of JSON files
  - id: pretty-format-json      # Format JSON files consistently
    exclude_types:
    - jupyter
    args:
    - --autofix
  - id: mixed-line-ending      # Ensure consistent line endings
